lints.workspace = true

[package]
name = "legix-note"
version = "0.2.0"
repository = "https://github.com/aicumene/legix"
license = "MIT OR Apache-2.0"
description = "A crate of legix, a fork of the gitoxide project dealing with git notes"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2024"
rust-version = "1.88"
include = ["/src/**/*", "/LICENSE-*"]

[lib]
doctest = false

[[bench]]
name = "read-write"
harness = false
path = "./benches/read_write.rs"

[package.metadata.docs.rs]
features = ["sha1"]

[features]
## Enable support for the SHA-1 hash by forwarding it to dependencies.
sha1 = ["legix-hash/sha1", "legix-object/sha1"]
## Enable support for the SHA-256 hash by forwarding it to dependencies.
sha256 = ["legix-hash/sha256", "legix-object/sha256"]

[dependencies]
legix-error = { version = "^0.4.0", path = "../legix-error" }
legix-hash = { version = "^0.27.0", path = "../legix-hash" }
legix-object = { version = "^0.65.0", path = "../legix-object" }

[dev-dependencies]
insta = "1.46.3"
criterion = "0.8.2"
legix-note = { path = ".", features = ["sha1", "sha256"] }
legix-odb = { path = "../legix-odb" }
legix-testtools = { path = "../tests/tools" }
