lints.workspace = true

[package]
name = "legix-commitgraph"
version = "0.40.0"
repository = "https://github.com/aicumene/legix"
documentation = "https://git-scm.com/docs/commit-graph"
license = "MIT OR Apache-2.0"
description = "Read-only access to the git commitgraph file format"
authors = ["Conor Davis <gitoxide@conor.fastmail.fm>", "Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2024"
include = ["/src/**/*", "/LICENSE-*"]
rust-version = "1.88"

[lib]
doctest = false

[features]
## Enable support for the SHA-1 hash by enabling the respective feature in the `legix-hash` crate.
sha1 = ["legix-hash/sha1"]
## Enable support for the SHA-256 hash by enabling the respective feature in the `legix-hash` crate.
sha256 = ["legix-hash/sha256"]
## Data structures implement `serde::Serialize` and `serde::Deserialize`
serde = ["dep:serde", "legix-hash/serde", "bstr/serde"]

[dependencies]
legix-hash = { version = "^0.27.0", path = "../legix-hash" }
legix-chunk = { version = "^0.9.0", path = "../legix-chunk" }
legix-error = { version = "^0.4.0", path = "../legix-error" }

bstr = { version = "1.12.0", default-features = false, features = ["std"] }
memmap2 = "0.9.11"
nonempty = "0.12.0"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
insta = "1.46.3"
legix-testtools = { path = "../tests/tools", default-features = false }
legix-date = { path = "../legix-date" }
legix-hash = { path = "../legix-hash", features = ["sha1", "sha256"] }

[package.metadata.docs.rs]
all-features = true
features = ["sha1", "document-features"]

[package.metadata.cargo-machete]
ignored = [
    # Needed for `bstr/serde` feature forwarding, even though no direct `bstr` paths are referenced.
    "bstr",
]
